platform :ios, '9.0'

target 'firetracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firetracker
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'OAuthSwift'
    pod 'SwiftSpinner'

end
